### ISSUE TITLE
Stuck in configure device screen

### ISSUE THREAD

**Issue by maxiimillian** [notmarek/LanguageBreak#11]
Hi there, just tried this on a kindle at version 5.16.2.1.1.
After selecting the standard demo type on step 4, it went to the screensaver with a box at the bottom saying
"This demonstration device is either missing content or is disconnected from the network"
"CONFIGURE DEVICE"

Clicking configure device does nothing and it no longer shows up as a device If I plug it into my pc.
The secret gesture doesn't do anything either.
Any way around this? Thanks.

**Comment by shipurjan** [comment]
You're probabbly doing the secret gesture wrong

https://www.youtube.com/watch?v=JzuIGbGPpig

**Comment by maxiimillian** [comment]
You are correct, thanks for the help. Might be worth adding this link to the guide since based on the comments I was not the only moron
