### ISSUE TITLE
Update_hotfix_languagebreak-{language you want to end up with}.bin doesnt appear to exist

### ISSUE THREAD

**Issue by sirus20x6** [notmarek/LanguageBreak#13]
directions unclear. no Update_hotfix_languagebreak-{language you want to end up with}.bin files in repo

**Comment by KameBA** [comment]
They are in the downloaded file (.tar.gz). Open it (I use 7zip), and copy the language you want.
![281212687-b27598c2-1ab9-469a-8124-29d0f461ad47 1](https://github.com/notmarek/LanguageBreak/assets/96673893/a20695f4-90e4-4194-aa41-430eb48f496c)
