### ISSUE TITLE
Cannot detect storage after Jailbreak

### ISSUE THREAD

**Issue by federicodilo** [notmarek/LanguageBreak#14]
Hello, 
I followed the guide step by step by having version 5.15.0.0 on my Kindle 11th gen.
By completing the procedure I had no luck since ";log" didn't show me anything. 
Then I decided to update, as written, to version 5.16.2.1.1. Unluckily just after the jailbreak procedure the Kindle, rebooting, showed me an error and a feedback request. After denying it, it reboots in Demo mode.
By typing ";uzb" it just freeze for a few seconds and then it goes back to the main screen. By connecting the Kindle to the PC, it is not beign detected.
However I cannot do anything more since the tile to access settings is grayed out and so airplane mode.
In the library it has happaerd just a log file which I can just access but I cannot, obviously, transfer to let it read you.

How can I fix this?

Thanks.

**Comment by notmarek** [comment]
Just reboot and ;uzb should work

**Comment by federicodilo** [comment]
Okay well, it has worked but now, after I copied the hotfix, the update option is grayed out since I'm in managed device mode. Any idea?

**Comment by federicodilo** [comment]
Well I completed the procedure once again, by booting a 5.12 is shown in the footer of the page, the folder mkk is shown on the root of the Kindle, but the ";log" command gives me still no result.

I will stay tuned for any suggestions. Thank you for your effort.

**Comment by federicodilo** [comment]
I tried again by doing a clean install.  After the jailbreak procedure it still shows a raise a bug prompt. In any case it leads to Demo mode and this is where the guide seems to slightly differ from what is presented.
I leave the log that is produced in the root of the Kindle and remain available for testing.

[all_logs_as_of_Wed_Nov_15_2023_08_53_34.tar.gz](https://github.com/notmarek/LanguageBreak/files/13362564/all_logs_as_of_Wed_Nov_15_2023_08_53_34.tar.gz)

**Comment by notmarek** [comment]
> I tried again by doing a clean install.  After the jailbreak procedure it still shows a raise a bug prompt. In any case it leads to Demo mode and this is where the guide seems to slightly differ from what is presented.
> 
> I leave the log that is produced in the root of the Kindle and remain available for testing.
> 
> 
> 
> [all_logs_as_of_Wed_Nov_15_2023_08_53_34.tar.gz](https://github.com/notmarek/LanguageBreak/files/13362564/all_logs_as_of_Wed_Nov_15_2023_08_53_34.tar.gz)
> 
> 

You are still in demo mode create a file called DONT_CHECK_BATTERY and do ;debug -> resell device

**Comment by federicodilo** [comment]
Kindle 11th gen.
Fixed by following the guide, but flashing niluje's [hotfix](https://storage.gra.cloud.ovh.net/v1/AUTH_2ac4bfee353948ec8ea7fd1710574097/mr-public/Touch/JailBreak-1.16.N-FW-5.x-hotfix.zip) from snapshot thread instead. 

Thanks to @notmarek & @NiLuJe.
