### ISSUE TITLE
Unable to exit managed mode without device being reset without mkk jailbreak files

### ISSUE THREAD

**Issue by xraywinedrinker** [notmarek/LanguageBreak#16]
I have a kindle 4 basic running 5.16.2.1.1 and I can get to the point of jailbreaking up to the hot fix but every time I try to exit managed mode by using ;demo, the device restarts and comes out of managed mode but loses the jailbreak. Any idea how to exit managed mode and retain the jb?

Here is the log file on the kindle.
[all_logs_as_of_Sat_Dec_02_2023_20_23_23.tar.gz](https://github.com/notmarek/LanguageBreak/files/13537297/all_logs_as_of_Sat_Dec_02_2023_20_23_23.tar.gz)

**Comment by notmarek** [comment]
Loses the JB? That should happen just reinstall the hotfix after exiting demo

**Comment by xraywinedrinker** [comment]
I just reinstalled the hot fix and I still have the mkk folders, thank you.
