### ISSUE TITLE
So, the kindle is jailbroken. What now?

### ISSUE THREAD

**Issue by ExoticMarbles** [notmarek/LanguageBreak#18]
I jailbroke my ancient 2nd Gen Kindle, which was admittedly easier than doing it to my new 11th Gen. Install MRPI? KUAL? All of those threads are nearly 6 years out of date, haha,

Some direction would be appreciated.

**Comment by notmarek** [comment]
All of the threads are old, yes, however they are not outdated, first install KUAL - the directions will start with installing mrpi. Then  you are basically done and can do anything  you want, install usbnet, koreader, play around :)

**Comment by ExoticMarbles** [comment]
Argh, it's driving me crazy. ";log mrpi" just displays "hush little
baby..." then...nothing. No log files, no anything, even after a couple of
reboots...

**Comment by notmarek** [comment]
Are you using the coplate version of KUAL and are you on kindle fw version <5.16.3

**Comment by ExoticMarbles** [comment]
Sorry, I completely forgot about this thread. 

For people looking for insight:
- Install KOReader (coplate)
- Install KTerm
- Install OTABinRename
as a start!
