### ISSUE TITLE
Stuck in managed mode

### ISSUE THREAD

**Issue by thatsthat** [notmarek/LanguageBreak#20]

**Comment by thatsthat** [comment]
I can't get out of managed mode since when I type the ;demo command I get a message: 'device already registered' and nothing else happens. If I reboot the device I remain in managed mode. Should I try the option 'resell device' on demo mode or will that mess things up?

**Comment by notmarek** [comment]
;enter_demo
Reboot
;demo
Resell device

**Comment by thatsthat** [comment]
That may work but I have to wait until battery drops below 70% for some strange reason, I close this until I can try and I will reopen in case it doesn't work.

**Comment by notmarek** [comment]
> That may work but I have to wait until battery drops below 70% for some strange reason, I close this until I can try and I will reopen in case it doesn't work.

Create a file called "DONT_CHECK_BATTERY"

**Comment by thatsthat** [comment]
Hi, I just followed your instructions, now after reboot I lost KUAL, no mkk folder, and when I type ;log mrpi I get 'mrpi is not installed' . FW version  is still the same. How should I proceed?

**Comment by notmarek** [comment]
Didn't work?

**Comment by thatsthat** [comment]
Not sure. See the answer I've just written above

**Comment by notmarek** [comment]
Install hotfix, then proceed to install kual according to the tutorial

**Comment by thatsthat** [comment]
It worked like a charm :+1:

**Comment by thatsthat** [comment]
It worked like a charm 👍

**Comment by imTHAI** [comment]
@notmarek @thatsthat 
It works but as soon as I login again into my amazon account with my Kindle, it seems that it's back into managed account.

I used the oneclick method for which I had to login my account following step 0. Isn't my account forever tagged as a managed account or something ?
