### ISSUE TITLE
5.16.2 Firmware Unavailable

### ISSUE THREAD

**Issue by momja** [notmarek/LanguageBreak#22]
Thanks for the jailbreak.

I have a Kindle ~Paperwhite~ 11th Gen on version 5.15.0, but I can't find a snapshot for 5.16.2 to install for this hardware. Should I keep searching for this binary, or install on 5.15.0?

**Comment by notmarek** [comment]
Should work fine on 5.15 (i did try it on a kt5 on this version a few days
ago) if you want 5.16 i will need to know what kindle you are using

**Comment by momja** [comment]
I'm on a Kindle Basic 4. Kindle (11th Gen). I realize I said I was on Kindle PW above, but that's incorrect.

**Comment by notmarek** [comment]
Thats KT5 so you should be fine as for the update you are looking for it's
here -
https://s3.amazonaws.com/firmwaredownloads/update_kindle_11th_5.16.2.1.1.bin

**Comment by momja** [comment]
Thanks! installing now. Sorry I had the wrong Hardware version. Will try to provide feedback with jailbreaking process.

**Comment by notmarek** [comment]
Thanks and goodluck
