### ISSUE TITLE
kindle 8, 5.16.2.1.1; after step 12, couldn't see language selection screen, and enter kindle with English system.

### ISSUE THREAD

**Issue by Ym9i** [notmarek/LanguageBreak#23]

**Comment by notmarek** [comment]
That suggest you are already jailbroken

**Comment by icyphox** [comment]
Can confirm, I'm running into the exact same situation. Steps 11-12 don't really work because the device reboots mid-copy, and it appears to be back in normal mode, in English.

**Comment by notmarek** [comment]
that is managed mode and the fact thats in English means you were
successful - what you need to do now is install the hotfix using UYK and
then exit managed mode using one of the described ways.

**Comment by icyphox** [comment]
Hm, not sure if it's in Managed Mode since I have all settings clickable (not greyed out), and applying the hotfix fails with the message "Update failed".

**Comment by sultanhq** [comment]
I also get the same problem (selected chinese after restart, saw the log with languagebreak, but then got english after that then failed in to install update of hotfix) on a PW 8 with 6.16.2.11

**Comment by ShOeLaYz** [comment]
Same Issue , I Dont See A Language Selection Screen Nor The Log Thing.
I Am On A Kindle 8th Gen Basic . with 5.16.2.1.1.
