### ISSUE TITLE
Kindle Oasis 9th Generation, 5.16.2.1.1 - Jailbreak Doesn't Work Following Step 13

### ISSUE THREAD

**Issue by uwubean** [notmarek/LanguageBreak#25]
I've tried following this guide multiple times, but it fails after step 13 each time. No log entries appear after rebooting (even though I select the Chinese language, which appears above a Pseudot entry), nor does any mkk folder appear. The ;log command only leads to a search results screen, too. I'm not sure what I'm doing wrong or what to try. The only abnormal thing that happens during installation is that I am unable to safely eject my Kindle during step 12; my computer freezes each time I try. Is there anything I can do?

**Comment by notmarek** [comment]
Have you tried installing the hotfix

**Comment by uwubean** [comment]
I have. It doesn't seem to do anything, as installing the en-us hotfix only seems to cause the device to reboot back into managed demo mode in the Chinese language. I've followed the five step reboot process outlined in the guide, but there's still no mkk folder present when I do so. I know that you can't provide support for mkk itself, but I can't find an oasis version of it on the mkk page on mobileread to install manually. Without being able to try that, I don't know how to proceed with troubleshooting.

**Comment by notmarek** [comment]
;demo - resell device

**Comment by uwubean** [comment]
Yes, I've done that. I've run through the process about five times, exactly as described above, but the log and mkk folder have never appeared. I can't seem to find a version of mkk on the mobileread forum to try to install manually, so I have no clue if the jailbreak worked. I don't think it has, because KUAL doesn't seem to function.

**Comment by notmarek** [comment]
When in non demo mode install the hotfix from nilujes thread

**Comment by uwubean** [comment]
No luck. I've also tried installing MRPI as outlined in this post to no avail. 
https://www.mobileread.com/forums/showpost.php?p=4367397&postcount=72

**Comment by NikolausB** [comment]
Hi there, I have the same issue with the same device when using the latest release. 
When using the current git verion from master branch (from dec 4th), i see a log message in step 14, but the jailbreak wont work either.
Installing hotfix only ends in an error message that the update could not be installed.
Any idea what I could try next?

Thanks in advance :)

**Comment by notmarek** [comment]
Use the compiled version in releases....

**Comment by NikolausB** [comment]
Sorry if I did not describe my issue correct.
I did use the latest compiled version, but that did not work at all (no log in step 14 and no jailbreak) as uwubean described above. 
Therefore i tried the non compiled verison and there happend to be a log in step 14. But the jailbreak did not work either.

**Comment by luna-null** [comment]
@NikolausB I had a very similar issue to yours. I have a kindle paper white gen 10, update 5.14.3.0.1, and I kept getting no log info and it kept giving a 007 error when trying to apply the hotfix.
https://www.mobileread.com/forums/showpost.php?p=4416668&postcount=832
Following this guide fixed it for me.

**Comment by NikolausB** [comment]
thanks @luna-null that did work for me as well :)
