### ISSUE TITLE
Stuck in weird state after jailbreak was installed

### ISSUE THREAD

**Issue by maxiimillian** [notmarek/LanguageBreak#27]
Hello, after doing all the steps I saw the log messages appear after the final reboot saying the jailbreak was finished.
After the reboot it booted back up to the screen from step 2 with the text fields. I went along and it booted back into demo mode but now ;demo, ;enter_demo, and ;uzb do nothing, and USB access isn't working.

Is this a known issue / mistake that I've made, and is there anything that can be done from this state?

**Comment by notmarek** [comment]
A reboot should fix it.

**Comment by ramjke** [comment]
> A reboot should fix it.

it's not

**Comment by maiiabocharova** [comment]
@ramjke Hello, were you able to fix it? I have also followed steps up to 13-14 and it showed a message that jailbreak successful, but it brought me to step 2 screen. Do not know what to do?

**Comment by ramjke** [comment]
> @ramjke Hello, were you able to fix it? I have also followed steps up to 13-14 and it showed a message that jailbreak successful, but it brought me to step 2 screen. Do not know what to do?

I don't know. I decided not to continue with the jailbreak.

**Comment by maiiabocharova** [comment]
> > @ramjke Hello, were you able to fix it? I have also followed steps up to 13-14 and it showed a message that jailbreak successful, but it brought me to step 2 screen. Do not know what to do?
> 
> I don't know. I decided not to continue with the jailbreak.

I was able to finish it actually! (So just input random stuff, like step 2. Then `;demo` -> `Resell device`. Afterward it reboots. Then you type `;log mrpi` - if it tells you that mrpi is not installed - bingo! We have our jailbroken Kindle). I already have KoReader on it.

So basically after step 14 I did not have to proceed. Only  `;demo` -> `Resell device` and that was it.
