### ISSUE TITLE
Support the Mi Gu version of Kindle？

### ISSUE THREAD

**Issue by songlee-gis** [notmarek/LanguageBreak#3]
Can I ask if this supports the Mi Gu version of Kindle (a special version for China)?

**Comment by notmarek** [comment]
can you send a link to its firmware download page?

**Comment by cyberzhuan** [comment]
[https://fireos-eink-src.s3.amazonaws.com/HawmZJqHBeyH28bnKI0dFD4Cih/update-kindle-6.6.0_user_660655220.bin](url)

Please refer to this link.

**Comment by notmarek** [comment]
> [https://fireos-eink-src.s3.amazonaws.com/HawmZJqHBeyH28bnKI0dFD4Cih/update-kindle-6.6.0_user_660655220.bin](url)
> 
> Please refer to this link.

Well then unfortunately no the Mi Gu isn't supported since it seems to be running FireOS which is android
