### ISSUE TITLE
[PW4 (10th)] Can't continue past step 9 - Need to wait for battery to discharge to enter shipping mode

### ISSUE THREAD

**Issue by alexindigo** [notmarek/LanguageBreak#30]
Can't continue past step 9 - Need to wait for battery to discharge to enter shipping mode

**Comment by notmarek** [comment]
Seems like you copied the files wrong. There's a file that tells the kindle
to skip this check so read the instructions carefully and copy the files
again.

**Comment by xXkr13g3rXx** [comment]
Copy the contents of the Languagebreak Folder to the root path

**Comment by alexindigo** [comment]
<img width="364" alt="Screenshot 2024-01-12 at 11 44 05 PM" src="https://github.com/notmarek/LanguageBreak/assets/127063/e41a6a56-d25d-4541-a75c-a3000a7c07fe">

This is what I copied.

Also, now it doesn't connect via USB, only charging.

**Comment by xXkr13g3rXx** [comment]
Yeah you need to copy the files within the „LanguageBreak“ (NOT the „LanguageBreak-16.11.23“) folder to the root path of the kindle.

**Comment by alexindigo** [comment]
Oh, this wasn't clear. I see. Thank you.

Do you know how I can make it to connect via USB again?

**Comment by argalad** [comment]
I am having the same issue with my Kindle Oasis, I have put the files inside LanguageBreak folder into the root folder of the Kindle but the warning still appears. Is there anything I can do? I have 97% battery right now so I guess I'll have to wait...

**Comment by alexindigo** [comment]
Found it: `;uzb`

**Comment by argalad** [comment]
> I am having the same issue with my Kindle Oasis, I have put the files inside LanguageBreak folder into the root folder of the Kindle but the warning still appears. Is there anything I can do? I have 97% battery right now so I guess I'll have to wait...

Solved it by restarting the kindle.
