### ISSUE TITLE
Issue on PW3 7th gen 5.16.2.1.1

### ISSUE THREAD

**Issue by Servalipp** [notmarek/LanguageBreak#32]
Everything goes very smoothly, I apply the hotfix, and my kindle becomes a "managed device", plugging it in shows the mkk folder. It is when I try to change it back to a normal device, that it removes all of those folders. The device is still jailbroken, as typing `log` in will show the text on the top left. But the file structure when I plug in the kindle just shows documents and fonts, as well as a log. There is no `mkk` folder.

**Comment by notmarek** [comment]
Install the hotfix again :)

**Comment by Servalipp** [comment]
Thanks for the reply :D This was my second time applying the hotfix still to no avail, I will try it again today, but do you figure if i just copied the files over from when I had them in the managed mode to the "unlocked" mode via file transfer, would it work? (i am very new to kindle jailbreaking)

**Comment by Servalipp** [comment]
Update, I applied the hotfix outside of the demo, and it worked. I was trying to install mrpi, but `;log mrpi` just says "Hush little baby" and KUAL is not running.

**Comment by Servalipp** [comment]
For anybody referencing this in the future, copying doesn't seem to work. Just apply the hotfix again in the non-demo mode, and it should work. That is, just "Update Kindle" from your normal mode.
