### ISSUE TITLE
Kindle touch firmware 5.3.7.3

### ISSUE THREAD

**Issue by abbottcam** [notmarek/LanguageBreak#35]
hello, 

Im not sure if this has been covered before, but how to I jailbreak a kindle touch? I can't get into demo mode, I typed ;enter_demo in the search bar at the top and restarted it, but nothing.

thanks

James

**Comment by notmarek** [comment]
Kindle touch is completely unrelated

**Comment by abbottcam** [comment]
Thanks for getting back to me...ah so, the kindle touch isn't compatible with this jailbreak?

**Comment by notmarek** [comment]
sorry mixed up kindle touch with fire, anyway search for kindle touch
jailbreak, you should be able to find one.
