### ISSUE TITLE
PW5 Signature 5.16.2.1.1: Device will not leave Managed Mode

### ISSUE THREAD

**Issue by KridOCaign** [notmarek/LanguageBreak#37]
I followed the steps as described, and applied the hotfix via the "Update Your Kindle" menu option
At no point did my Kindle switch to Chinese language.
The MKK folder did generate itself.

**Comment by KridOCaign** [comment]
I have found the solution. The instructions need to be updated for Paperwhite Signature Edition kindles.
I'm not sure why the signature edition behaves differently, and I am unable to return my kindle to a fully non-jailbroken state, but here are the steps I took which corrected the issue:

1: Use the Resell option
2: After it finishes restarting, factory reset the kindle.
3: Do not enter demo mode or access the demo menu after this point.
4: After it finishes restarting, install the official firmware for 5.16.1.1.1 via USB.
5: After it finishes restarting the Kindle will still be jailbroken, but will no longer be in managed mode. The MKK folder will not be present. Put the hotfix in the root of your device and install it via the UYK menu option.

It should now be out of managed mode and and correctly jailbroken.

**Comment by hlopez94** [comment]
What does UYK mean?

**Comment by kompeigompei** [comment]
> 4: After it finishes restarting, install the official firmware for 5.16.1.1.1 via USB.
Was this a typo of 5.16.2.1.1 (the recommended firmware version)? Or does the firmware need to be on this specific version?

**Comment by kompeigompei** [comment]
> What does UYK mean?

Abbreviation for "Update Your Kindle" (3 dot menu in the upper-right hand corner in Settings)
