### ISSUE TITLE
PW3 (G090G1): No `mkk` folder after completion of steps.

### ISSUE THREAD

**Issue by abhigyantrips** [notmarek/LanguageBreak#38]
I've followed through with all the steps, including exiting Managed Mode. Logged into my Amazon account after joining the Wi-Fi and stuff, and the registration happened successfully.

I can see text on the top left when I enter `;log` in Kindle Search, but plugging the Kindle into my system only shows the following three folders.

![image](https://github.com/notmarek/LanguageBreak/assets/28886624/721e4302-358d-4751-a6af-e6655b61ca42)

Any help would be appreciated.

**Comment by abhigyantrips** [comment]
That works, thank you! Can I know why the hotfix install didn't work the first time? Or is that kinda random?

**Comment by notmarek** [comment]
Because you installed the hotfix only before resetting

**Comment by abhigyantrips** [comment]
I see, I'll keep that in mind. Thanks again :)
