### ISSUE TITLE
(following the method in issue 34 with multiple re-installs) on firmware 5.16.2.1.1 (PW4 7th. Gen)

### ISSUE THREAD

**Issue by FennekFox19** [notmarek/LanguageBreak#39]
KPPWMain V2 error log (crash of the main menu)

**Comment by FennekFox19** [comment]
Currently trying to set the device up in chineese and start to follow the guide after that (maybe, it is related to language errors)

**Comment by FennekFox19** [comment]
![image](https://github.com/notmarek/LanguageBreak/assets/101789389/ece12a35-f56b-48c0-bff7-ce8fa30a49b1)
First fw install

**Comment by FennekFox19** [comment]
Factory restore number 2

**Comment by FennekFox19** [comment]
Here is the fw file
![image](https://github.com/notmarek/LanguageBreak/assets/101789389/cc1f0865-fa38-449a-9ea3-7efb61923cde)

**Comment by FennekFox19** [comment]
Problem still exists

**Comment by FennekFox19** [comment]
It is related to my model in general. Sorry

**Comment by FennekFox19** [comment]
Or maybe not and the latest compile fucked up?

**Comment by alowva** [comment]
You have just spammed anyone that has notifications on with 11 messages, please don't do that!
There is no need to have separate messages for each sentence or screenshot.
Take your time to compile all the information you have in one message and until someone replies just edit the first message.
Despite all these messages you still haven't fully described your issue.

There has been no recent compile or commit that would have broken this, you're probably doing something wrong. Slow down and make sure you try each step FULLY

**Comment by FennekFox19** [comment]
Sorry.
I was really nervous.
I did every step fully and am now past the resell screen (the one with power that needs to be done fast)
I am now at another demo setup screen.
What should i do next?

**Comment by FennekFox19** [comment]
[KPPMainAppV2_5488_002-juno_16020101_muscat_wario-409747_crash_Apr_02_17.37.06_2024.txt](https://github.com/notmarek/LanguageBreak/files/14841841/KPPMainAppV2_5488_002-juno_16020101_muscat_wario-409747_crash_Apr_02_17.37.06_2024.txt)

**Comment by FennekFox19** [comment]
I managed to do a force reboot during resell logo and nothing happened (no boot splash after reboot)

**Comment by isovector** [comment]
For what it's worth, mine crashed as well during startup immediately after the jailbreak, but I closed the dialog and a few minutes later everything worked as expected.

**Comment by notmarek** [comment]
It crashes its expected if you don't want core dump popups create a file named "DISABLE_CORE_DUMP" or figure out why it happens yourself
