### ISSUE TITLE
No log message at step 14

### ISSUE THREAD

**Issue by NoAccount1** [notmarek/LanguageBreak#42]
Hello
I tried multiple times to jailbreak my kindle (PW3 on 5.16.2.2.1).
I went through all steps but newer got a log message at step 14.

PSEUDOT option was available at language selection.

Also, each time i tried to apply the hotfix fr_FR then en_US (fr_FR but was reported not working on #28), I tried reinstalling fresh 5.16.2.2.1 and reset my kindle multiple times but I still can't jailbreak

Do you have any idea what to do ?
Thank you in advance

**Comment by NikolausB** [comment]
Is your firmware version really 5.16.2.**2**.1? Because the jailbreak only works for version <= 5.16.2.**1**.1 i believe.

**Comment by NoAccount1** [comment]
Woops sorry, I actually am in 5.16.2.1.1

**Comment by notmarek** [comment]
https://www.mobileread.com/forums/showpost.php?p=4416668&postcount=832 Try this i guess

**Comment by rluetzner** [comment]
Thank you so much @notmarek !!!

I tried the steps from the README at least 5 times and never got it to work. The link you posted [here](https://github.com/notmarek/LanguageBreak/issues/42#issuecomment-2133671007) worked right away. I was using a Kindle Paperwhite 3 with the "latest" firmware, which is 5.14.3.0.1.

Thanks for all the hard work. :partying_face: 

Maybe it'd make sense to point to this alternative from somewhere in the README. Something like

> If you tried this process multiple times and didn't see any log messages, have a look at issue #42 or https://www.mobileread.com/forums/showpost.php?p=4416668&postcount=832 .
