### ISSUE TITLE
No MKK folder after installing hotfix

### ISSUE THREAD

**Issue by Inqurity** [notmarek/LanguageBreak#45]
After installing the hotfix, the steps after didn't exit the managed mode. And there's no mkk folder appearing either.
The hotfix supposedly installed incorrectly, as writing ;log in the search bar does nothing

**Comment by Inqurity** [comment]
Have tried to install the hotfix again, ;log works now

**Comment by Inqurity** [comment]
And it worked! I successfully exited managed mode. Don't know why the hotfix didn't install on the first try, maybe because of the language? (first time i tried en-US and second time en-GB) Anyway, that fixed it. Still no mkk folder, but I managed to install KUAL without problems

**Comment by Inqurity** [comment]
Actually, this may still be an issue, none of my KUAL apps run, they just send me to the home screen

**Comment by Inqurity** [comment]
Turns out MKK is essential for running custom apps, but since it didn't install with the hotfix, i'll try installing it manually

**Comment by Inqurity** [comment]
And you can't install MKK manually on a Paperwhite 3. Sorry if this is hard to read, but I'm new to Kindle jailbreaking

**Comment by Inqurity** [comment]
Here's the log, if it helps
[all_logs_as_of_Sat_Jun_01_2024_18_35_43.tar.gz](https://github.com/user-attachments/files/15522925/all_logs_as_of_Sat_Jun_01_2024_18_35_43.tar.gz)

**Comment by Inqurity** [comment]
I've put my Kindle into Russian, rebooted, installed the Russian hotfix and now it's there. I believe the guide should be updated with like a little foot-note in case this happens to anyone else.

**Comment by Inqurity** [comment]
The instructions say the next:
Connect the device to a PC and copy whichever Update_hotfix_languagebreak-{languge/locale}.bin file matches **your** language to the Kindle's root directory.
Your language here is not a language of your choosing, but the language the Kindle is in, which is most likely Chinese. I think this part should be corrected.

**Comment by Inqurity** [comment]
And there was another closed issue about this, sorry for making another one

**Comment by Kast555** [comment]
> The instructions say the next: Connect the device to a PC and copy whichever Update_hotfix_languagebreak-{languge/locale}.bin file matches **your** language to the Kindle's root directory. Your language here is not a language of your choosing, but the language the Kindle is in, which is most likely Chinese. I think this part should be corrected. The language is defaulted into English after the next step anyway, so **your** language may be confusing

Hey inqurity i'm having the same issue you had. I installed the hotfix (I think. Well ;log works) But I think I did the wrong lang. There was a step where we were told to select Chinese and then later we had to install a lang pack. I picked Eng. I think I was suppose to pick Chinese in that second step. Is that what you are saying above? Help break down what you did wrong and what you should have do diffrent because I'm having the same issue.

**Comment by Inqurity** [comment]
> Hey inqurity i'm having the same issue you had. I installed the hotfix (I think. Well ;log works) But I think I did the wrong lang. There was a step where we were told to select Chinese and then later we had to install a lang pack. I picked Eng. I think I was suppose to pick Chinese in that second step. Is that what you are saying above? Help break down what you did wrong and what you should have do diffrent because I'm having the same issue.

I'd be happy to help, but I really just don't remember what I did back then. But yes, I think I did pick English, just like you described.
Please refer to #48 for further instructions, they seem to have helped other people.
