### ISSUE TITLE
No chinese + no mkk folder

### ISSUE THREAD

**Issue by 155c5e** [notmarek/LanguageBreak#46]
After following all the steps, and repeating them after reflashing the OS .bin, my pw3 never went into chinese language and even though upon using the ;log command i get some text on the screen, there is no mkk folder. any idea of how i can fix this? or was i succesful and just don't have the mkk folder for some reason

**Comment by FennekFox19** [comment]
fix was found in issue that mentioned this issue.
this issue can be closed
