### ISSUE TITLE
REQUEST - add a pool for devices & firmware versions where the oneclick method works

### ISSUE THREAD

**Issue by FennekFox19** [notmarek/LanguageBreak#50]
Look at the header

**Comment by FennekFox19** [comment]
it did on my pw3 on the second attempt (did put me in chinese demo mode after reboot)

**Comment by notmarek** [comment]
Oh wow, it should technically work on everything supported by language break since it does the same stuff just in a very dumb way 😅

**Comment by FennekFox19** [comment]
I will do a recording of the process and send it to you via mail, if thats ok to you.
(btw, I'm the guy with an issue fom over a year or so ago)

**Comment by FennekFox19** [comment]
It might also be related to the fact that I was logged into my amazon account prior to running the oneclick method.

**Comment by notmarek** [comment]
> It might also be related to the fact that I was logged into my amazon account prior to running the oneclick method.

the one click method wont work if your device isnt registered since you cant use the store, i think i mention this somewhere

**Comment by FennekFox19** [comment]
you did not

**Comment by FennekFox19** [comment]
No problem.
That happens to me all the time at work (forgetting the little thing that will blow everything to dust if not done)
