### ISSUE TITLE
Stuck with screensaver after demo mode reboot

### ISSUE THREAD

**Issue by kongjudas** [notmarek/LanguageBreak#52]
My PW3 is stuck at the screensaver after first reboot after entering `;enter_demo`. I had set a passkey, so it only asks me for that and goes back to the screensaver. Have tried the 40 sek. restart, but no cigar.
Edit: It doesn't connect with USB to my Mac either, so, please help....

**Comment by notmarek** [comment]
Enter `111222777` it will clean the passcode and reset your kindle
