### ISSUE TITLE
What this jailbreak does?

### ISSUE THREAD

**Issue by Gendozz505** [notmarek/LanguageBreak#55]
Hello,

Could you please explain the pros of this jailbreak? Does it allow you only to change the system language or provide additional features like reading fb2 format and more?

P.S. Do I have to instal the hotfix or its needed only for some missing languages?

Thank you,
Genadi

**Comment by notmarek** [comment]
It's just a jailbreak all it does is allow you to sideload updates signed
with developer keys - eg install j hotfix/Kual/koreader etc.
