### ISSUE TITLE
[QUESTION] Can I log in to my Amazon account after jailbreak?

### ISSUE THREAD

**Issue by Yoddikko** [notmarek/LanguageBreak#63]
As the title says, I would like to know if it's possible to login to my kindle account after jailbreak.

**Comment by notmarek** [comment]
Yes, no changes are made to the official systwm

**Comment by Yoddikko** [comment]
Thanks a lot, sorry for opening a issue, didn't know where to ask!

**Comment by notmarek** [comment]
It's fine :)
