### ISSUE TITLE
A lot of people find this guide very convoluted.

### ISSUE THREAD

**Issue by wuulfy** [notmarek/LanguageBreak#7]
### Some critiques:

1 - The "Post Post Jailbreak" (from the MobileRead version of the guide) section is missing from this version of the guide despite having useful information to help succeed with jailbreak (which I needed when trying this on my own device).
2 - There is no clear way to check if the jailbreak completely succeeded following the "Post Jailbreak" section or is unmentioned in this guide, creating some scepticism.
3 - Step 15 is ambiguous and fails to tell the user that they have to plug the Kindle in **the immediate second** the press to power on screen shows up.
4 - Absolutely no information on what you can do once the Kindle is jailbroken. This isn't uncommon but it would be a nice-to-have since there isn't a lot of documentation on Kindle JB as it is.
5 - This doesn't actually work on _every_ firmware version below 5.16.2.1.1 as this guide seems to suggest - its probably best to recommend that the user is running a version around 5.16.x.x.x or upgrade directly to 5.16.2.1.1 while explaining how to update firmware version _before_ the 24 steps. In my experience, 5.14.x.x and below are incompatible and found most luck upgrading to 5.16.x.x.x.
6 - Some steps could just be merged into one to make this guide easier to digest. For example, 12-13 can be merged to say 
"Select the "Resell Device" option and press Yes/Resell".
7 - As the other issue mentioned, this guide doesn't actually tell the user where in the tar file you can find the hotfix updates which causes confusion.

**Comment by notmarek** [comment]
Hope you find my changes in commit 88407af suitable.

**Comment by wuulfy** [comment]
This is a big improvement - I'm hoping this makes things more digestible for some because I had noticed quite a lot of commenters having trouble with the original guide (along with personal gripes) especially for newcomers to Kindle jailbreak. On a side note, I apologise if my criticism came off heavy handed.

Thank you, this is a lot better

**Comment by notmarek** [comment]
> This is a big improvement - I'm hoping this makes things more digestible for some because I had noticed quite a lot of commenters having trouble with the original guide (along with personal gripes) especially for newcomers to Kindle jailbreak. On a side note, I apologise if my criticism came off heavy handed.
> 
> Thank you, this is a lot better
Thanks,
If you have any other improvements you'd like to make, please open an issue or a pull requests with the actual changes, I myself am a newcomer to the kindle community

**Comment by ali-oem** [comment]
Also, please add to step 10 that if the kindle battery is over 70%, it will show shipping mode error, [Clarification](https://www.mobileread.com/forums/showthread.php?t=174481)

**Comment by notmarek** [comment]
This is prevented by the DONT_Check_battery file

> Also, please add to step 10 that if the kindle battery is over 70%, it will show shipping mode error, [Clarification](https://www.mobileread.com/forums/showthread.php?t=174481)

**Comment by ali-oem** [comment]
So why I'm seeing it?

**Comment by notmarek** [comment]
> So why I'm seeing it?

Did you copy all the files correctly?

**Comment by ali-oem** [comment]
> > So why I'm seeing it?
> 
> Did you copy all the files correctly?

Ah yes my bad, I copied the master folder instead, I managed to Jailbreak it and install KUAL , Thank you so much kind person.
