### ISSUE TITLE
Can I turn on wifi after jailbreak?

### ISSUE THREAD

**Issue by shipurjan** [notmarek/LanguageBreak#8]
First of all thanks for this jailbreak :) I've been waiting for it

But I've never done it before, so I have a question, can I turn the wifi back on and it won't install the newer firmware?

**Comment by Cluck-Nugget** [comment]
I wouldn't turn wi-fi on if there's a new firmware available; you should install kual and helper to turn updates off.

**Comment by notmarek** [comment]
As @Cluck-Nugget said you can turn on wifi but beware there be dragons - stealthy ones waiting for their chance to update your device when you least expect it - so install kual and so on then  also get renameotabin extension that **should** protect you from the stealthy dragons (or maybe they are ninja cats who knows)
