### ISSUE TITLE
Hotfix error

### ISSUE THREAD

**Issue by yuantianle** [notmarek/LanguageBreak#9]
My jail break was successful, however, I cannot install any hotfix correct but get the error when the kindle was rebooting. How should I solve this problem?
![ac580423e273559c07a5bcd1b1de64b](https://github.com/notmarek/LanguageBreak/assets/61530469/8b6b337e-a7f8-4af9-a3f5-6b9864cf8e8b)

I am sure I used the newest hotfix file, but for the jailbreak files, I used the oldest one of LanguageBreak.
![image](https://github.com/notmarek/LanguageBreak/assets/61530469/b27598c2-1ab9-469a-8124-29d0f461ad47)

**Comment by notmarek** [comment]
> My jail break was successful, however, I cannot install any hotfix correct but get the error when the kindle was rebooting. How should I solve this problem?
> 
> ![ac580423e273559c07a5bcd1b1de64b](https://github.com/notmarek/LanguageBreak/assets/61530469/8b6b337e-a7f8-4af9-a3f5-6b9864cf8e8b)
> 
> 
> 
> I am sure I used the newest hotfix file, but for the jailbreak files, I used the oldest one of LanguageBreak.
> 
> ![image](https://github.com/notmarek/LanguageBreak/assets/61530469/b27598c2-1ab9-469a-8124-29d0f461ad47)
> 
>  

Make sure you use the latest files.
